### ISSUE TITLE
Not actually Turing-complete

### ISSUE THREAD

**Issue by Eiim** [thesephist/tabloid#3]
As much as I love this incredible, useful language, it unfortunately seems to lack any way to take input, unless I'm missing something (and I'm not sure how I would be). As I'm sure you're aware, Turing machines require a way to take input and process it as output. Tabloid programs can only produce a fixed output. May I suggest something like "WHAT'S THE LATEST NEWS ON" to take input in some way?

**Comment by thesephist** [comment]
Touche @Eiim! Thanks for pointing out this detail.

In https://github.com/thesephist/tabloid/commit/25bc958e04878195347d27ecb7fe074dc3895911 I've added the keyword `LATEST NEWS ON` (just shortened it for sake of length :) to take user input. In the web UI / website, this pops up a `window.prompt()`.

You can try it with this Tabloid program:

```
EXPERTS CLAIM name TO BE
    LATEST NEWS ON 'What\'s your name?'
YOU WON'T WANT TO MISS 'Your name is ' PLUS name

PLEASE LIKE AND SUBSCRIBE
```
