### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by F8ER** [thesephist/tabloid#5]
Dear Developers of the project,

Thank you for the project.

May I ask if it's possible to leave comments in that code?
We didn't notice such implemented in the language parser.

Best and kind regards

**Comment by thesephist** [comment]
Tabloid currently doesn't support comments. Given the way the parser is built, it would be pretty tricky to add line comments `// like this` (the tokenizer doesn't know about newlines), but might be not that hard to add block comments delimited on both sides with words like `STARTCOMMENT BLAH BLAH BLAH ENDCOMMENT` or something similar.

You're welcome to fork the repo and try to add support for comments, I might accept a pull request. But you're right—the parser currently doesn't support it.

**Comment by F8ER** [comment]
`RUMORS SAY` `comment` `BUT QUESTIONABLE`
`RUMORS SAY` `comment` `BUT WHO KNOWS`

**Comment by thesephist** [comment]
Closed since this issue hasn't seen much progress since January, but if there's a pull request to add comment support, I'm still open to adding it :)

`RUMORS SAY` is a little weird as a keyword because it conflicts somewhat with the `RUMOR HAS IT` keyword, but perhaps something else similar?
