### ISSUE TITLE
And keyword?

### ISSUE THREAD

**Issue by ycl310** [thesephist/tabloid#7]
Does the "and" keyword exist for if conditions?

**Comment by thesephist** [comment]
Added them in the, uh, documentation.... in 7043fe47a91e08cfd04225259c8aaecbc45b33d6


<img width="366" alt="Screen Shot 2021-03-30 at 11 16 58" src="https://user-images.githubusercontent.com/5403917/113013149-749cb800-9149-11eb-8061-06fd0a7e4b36.png">
